#!/bin/bash
# Stop tracking perf captures, keep the text results, commit.
# Run from the repository root (the directory containing .git).
set -eu

[ -d .git ] || { echo "ERROR: no .git here. cd to the repo root first."; exit 1; }

echo "[1/4] untracking perf captures (local files are kept)..."
git rm --cached -r --ignore-unmatch -- \
    '*.perf.data' '*.perf.data.old' 'perf.data' 'perf.data.old' \
    '*.so' 'nbody_core.c' || true

echo "[2/4] updating .gitignore..."
if ! grep -q "^\*\.perf\.data$" .gitignore 2>/dev/null; then
cat >> .gitignore <<'GI'

# --- added for the nbody / pyflate optimization work ---
# perf captures: large, binary, and meaningless on another machine
*.perf.data
*.perf.data.old
perf.data
perf.data.old
*.folded

# Cython build products, regenerated by setup.sh
*.so
nbody_core.c
build/
__pycache__/
*.pyc

# copied from the installed benchmark by setup.sh
bm_pyflate_opt*/data/*.tar.bz2

# local virtualenvs
venv-release/
GI
    echo "      appended"
else
    echo "      already present, skipped"
fi

echo "[3/4] staging text results and scripts..."
git add -A

echo "[4/4] what will be committed:"
git status --short
echo
echo "Sizes staged (largest 10):"
git diff --cached --name-only | while read -r f; do
    [ -f "$f" ] && du -h "$f"
done | sort -rh | head -10

echo
read -r -p "Commit these changes? [y/N] " ans
case "$ans" in
    [yY]*)
        git commit -m "Add optimization results; stop tracking perf captures"
        echo
        echo "Committed. To undo without losing the changes:  git reset --soft HEAD~1"
        echo "Then push when ready:  git push"
        ;;
    *)  echo "Nothing committed. Files remain staged; 'git reset' to unstage." ;;
esac
